"""empty message

Revision ID: 25a011dff33c
Revises: 1b668820394c
Create Date: 2022-11-09 11:36:41.760399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a011dff33c'
down_revision = '1b668820394c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish_list', sa.Column('property_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish_list', 'property_id')
    # ### end Alembic commands ###
