"""empty message

Revision ID: 427e54addc01
Revises: b1374931fcf8
Create Date: 2022-11-09 09:20:03.493155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427e54addc01'
down_revision = 'b1374931fcf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish_list', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish_list', 'test')
    # ### end Alembic commands ###
