"""empty message

Revision ID: 51020e85dfa4
Revises: e03b45280f6a
Create Date: 2022-11-01 23:59:28.605133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51020e85dfa4'
down_revision = 'e03b45280f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agent', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('isAgent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isAgent')
    op.drop_constraint(None, 'agent', type_='foreignkey')
    op.drop_column('agent', 'user_id')
    # ### end Alembic commands ###
