"""empty message

Revision ID: b1374931fcf8
Revises: 51020e85dfa4
Create Date: 2022-11-02 13:51:01.641414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1374931fcf8'
down_revision = '51020e85dfa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('agent', sa.Column('twitter', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'twitter')
    op.drop_column('agent', 'bio')
    # ### end Alembic commands ###
