"""empty message

Revision ID: f49583972f1c
Revises: a277c3390791
Create Date: 2022-09-28 11:46:13.100296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49583972f1c'
down_revision = 'a277c3390791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('phonenumber', sa.Integer(), nullable=True))
    op.add_column('agent', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('agent', 'Email')
    op.drop_column('agent', 'PhoneNumber')
    op.add_column('properties', sa.Column('view1', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('view2', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('view3', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('view4', sa.String(), nullable=True))
    op.drop_column('properties', 'View1')
    op.drop_column('properties', 'View4')
    op.drop_column('properties', 'View3')
    op.drop_column('properties', 'View2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('View2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('View3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('View4', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('View1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('properties', 'view4')
    op.drop_column('properties', 'view3')
    op.drop_column('properties', 'view2')
    op.drop_column('properties', 'view1')
    op.add_column('agent', sa.Column('PhoneNumber', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('agent', sa.Column('Email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('agent', 'email')
    op.drop_column('agent', 'phonenumber')
    # ### end Alembic commands ###
